# Theo AO Rashid -- May 2020

# ----- BYM model -----
# Negative binomial likelihood
#
# Common terms (normal prior) +
# BYM for each LSOA +
# Age effects (random walk prior) +
# Age-LSOA interaction (normal prior) +
# Age-time interaction (random walk prior) +
# LSOA-time interaction (random walk prior)
# --------------------

library(rgdal)
library(spdep)
library(RCurl)
library(dplyr)
library(nimble)
library(lme4)

set.seed(1)

# ----- IMPORT DATA -----
# Mortality data
# url <- getURL("https://media.githubusercontent.com/media/theorashid/mortality-statsmodel/master/Data/mortsim.csv") # London
url <- getURL("https://raw.githubusercontent.com/theorashid/mortality-statsmodel/master/Data/mortsim_hf.csv") # Hammersmith and Fulham
mortality <- read.csv(text = url) %>%
  select(-X) # remove autogenerated column

mortality_m <- mortality %>% # Select male sex
  filter(sex == 1) %>%
  select(-sex)

# Shape data
shapefile <- readOGR(dsn = "Data/shapefiles/ldn_LSOA11",
                layer = "LSOA11_London")

# Merge with mortality
colnames(shapefile@data)[1] <- "LSOA2011"
shapefile <- merge(shapefile, distinct(select(mortality_m, LSOA2011, LSOA.id, LAD.id)))
shapefile <- shapefile[!is.na(shapefile$LSOA.id) ,] # remove NA rows for subsetting (Hammersmith and Fulahm)
shapefile <- shapefile[order(shapefile$LSOA.id),] # reorder on LSOA.id
row.names(shapefile@data) <- shapefile@data$LSOA.id

# Extract adjacency matrix
W.nb <- poly2nb(shapefile, row.names = rownames(shapefile@data))
nbInfo <- nb2WB(W.nb)
# adj = nbInfo$adj, weights = nbInfo$weights, num = nbInfo$num

# ----- INITIAL VALUES -----
# Get good initial values to avoid long burn ins.
# model with only age intercepts, LSOA intercepts and LSOA slopes
mod <- glmer(deaths ~ offset(log(population)) + LSOA.id + (1|age_group.id) + (1 + YEAR.id|LSOA.id), family = "poisson", data = subset(mortality_m, population > 0))

fixed <- coef(summary(mod))[, "Estimate"] # fixed effects
intercept <- fixed[1]
slope <- fixed[2]

bin <- ranef(mod)$LSOA.id
lsoa_int_inits <- bin$"(Intercept)"
lsoa_slope_inits <- bin$YEAR.id

bin <- ranef(mod)$age_group.id
age_inits <- bin$"(Intercept)"

initial <- list(intercept, slope, lsoa_int_inits, lsoa_slope_inits, age_inits)
names(initial) <- c("global.intercept", "global.slope", "lsoa.intercepts", "lsoa.slopes", "age.intercepts")


# Dimensions (Hammersmith and Fulham unit test second value):
# - age -- 19 (0, 1-4, 5-10, ..., 80-84, 85+)
# - LAD -- 33 or 1
# - MSOA -- 983 or 25
# - LSOA -- 4835 or 113
# - YEAR -- 14 (2004-17)

# ----- BUILD THE MODEL -----
# Indices:
# - a -- age
# - j -- space, each LSOA
# - t -- year (time)
code <- nimbleCode({
  # PRIORS
  # COMMON TERMS
  alpha0 ~ dnorm(0, 0.00001)
  beta0  ~ dnorm(0, 0.00001)
  
  # AREA TERMS -- BYM prior for LSOAs (not BYM2 as do not need to interpret)
  # No hierarchy
  # Structured intercept and slope with a CAR prior
  alpha_u[1:N_LSOA] ~ dcar_normal(adj[1:L], weights[1:L], num[1:N_LSOA], tau_alpha_u, zero_mean = 0)
  beta_u[1:N_LSOA]  ~ dcar_normal(adj[1:L], weights[1:L], num[1:N_LSOA], tau_beta_u, zero_mean = 0)
  # Unstructured IID intercept and slope
  for(j in 1:N_LSOA){
    alpha_v[j] ~ dnorm(alpha0 + alpha_u[j], sd = sigma_alpha_v) # centred on common + CAR term
    beta_v[j]  ~ dnorm(beta0 + beta_u[j], sd = sigma_beta_v)
  }
  sigma_alpha_u ~ dunif(0,2)
  tau_alpha_u <- pow(sigma_alpha_u,-2)
  sigma_beta_u ~ dunif(0,2)
  tau_beta_u <- pow(sigma_beta_u,-2)
  sigma_alpha_v ~ dunif(0,2)
  sigma_beta_v ~ dunif(0,2)
  
  # AGE TERMS
  alpha_age[1] <- 0 # initialise first terms for RW
  beta_age[1]  <- 0
  for(a in 2:N_age_groups){
    alpha_age[a] ~ dnorm(alpha_age[a-1], sd = sigma_alpha_age) # RW based on previous age group
    beta_age[a]  ~ dnorm(beta_age[a-1], sd = sigma_beta_age)
  }
  sigma_alpha_age ~ dunif(0,2)
  sigma_beta_age ~ dunif(0,2)
  
  # INTERACTIONS
  # age-LSOA interactions
  for(a in 1:N_age_groups){
    for(j in 1:N_LSOA){
      xi[a, j] ~ dnorm(alpha_age[a] + alpha_v[j], sd = sigma_xi) # centred on age + LSOA term
    }
  }
  sigma_xi ~ dunif(0,2)
  
  # LSOA-time interactions
  for(j in 1:N_LSOA){
    nu[j, 1] <- 0
    for(t in 2:N_year){
      # the difference between timesteps is beta_v * time (where timestep length is 1 year)
      nu[j, t] ~ dnorm(nu[j, t-1] + beta_v[j], sd = sigma_nu) # beta_v incorporates beta term
    }
  }
  sigma_nu ~ dunif(0,2)
  
  # age-time interactions
  for(a in 1:N_age_groups){
    gamma[a, 1] <- 0
    for(t in 2:N_year){
      # the difference between timesteps is beta_age * time (where timestep length is 1 year)
      gamma[a, t] ~ dnorm(gamma[a, t-1] + beta_age[a], sd = sigma_gamma)
    }
  }
  sigma_gamma ~ dunif(0,2)
  
  # Put all parameters together into indexed lograte with age-LSOA-time overdispersion term
  for(a in 1:N_age_groups){
    for(j in 1:N_LSOA){
      for(t in 1:N_year){
        lograte[a, j, t] <- xi[a, j] + nu[j, t] + gamma[a, t]
      }
    }
  }

  # LIKELIHOOD
  # N total number of cells, i.e. ages*years*areas(*sex)
  for (i in 1:N) {
    # y is number of deaths in that cell
    # mu is predicted number of deaths in that cell
    y[i] ~ dnegbin(p[i], r)
    p[i] <- r/(r + mu[i])
    log(mu[i]) <- log(n[i]) + lograte[age[i], LSOA[i], yr[i]]
  }
  r ~ dunif(0,50)
})

constants <- list(N = nrow(mortality_m),
                  N_year = n_distinct(mortality_m$YEAR),
                  N_LSOA = n_distinct(mortality_m$LSOA2011),
                  N_age_groups = n_distinct(mortality_m$age_group),
                  L = length(nbInfo$adj), 
                  adj = nbInfo$adj,
                  weights = nbInfo$weights,
                  num = nbInfo$num,
                  age = mortality_m$age_group.id,
                  LSOA = mortality_m$LSOA.id,
                  yr = mortality_m$YEAR.id)
data <- list(y = mortality_m$deaths,
             n = mortality_m$population)

# Initial values for uninformative priors (top-level nodes)
# mu, lograte, alpha_age, beta_age not initialised
inits <- list(alpha0 = initial$global.intercept,
			        beta0 = initial$global.slope,
			        alpha_u = initial$lsoa.intercepts,
			        beta_u = initial$lsoa.slopes,
			        alpha_age = initial$age.intercepts,
              sigma_alpha_u = 0.1, sigma_beta_u = 0.1,
              sigma_alpha_v = 0.1, sigma_beta_v = 0.1,
              sigma_alpha_age = 0.75, sigma_beta_age = 0.015,
              sigma_xi = 0.08, sigma_nu = 0.1,
              sigma_gamma = 0.1, r = 1.0)

# ----- CREATE THE MODEL -----
model <- nimbleModel(code = code, constants = constants, inits = inits, data = data) # model in R
# model$getNodeNames() # look at nodes of model's DAG
# model$plotGraph() # plot the DAG

# ----- COMPILE THE MODEL IN C-CODE -----
Cmodel <- compileNimble(model)

# ----- MCMC INTEGRATION -----
# Monitors
# Monitor the death rate per person to avoid 0 population issues
monitors <- c("lograte")
# Hyperparameter monitors to check covergence, with some thinning
sigmas <- c("sigma_alpha_u", "sigma_beta_u", "sigma_alpha_v",
            "sigma_beta_v", "sigma_alpha_age", "sigma_beta_age",
            "sigma_xi", "sigma_nu", "sigma_gamma")
monitors2 <- c("alpha0", "beta0", "r", sigmas)

# CUSTOMISABLE MCMC -- configureMCMC, buildMCMC, compileNimble, runMCMC
# 1. MCMC Configuration -- can be customised with different samplers
mcmcConf <- configureMCMC(model = Cmodel,
                          monitors = monitors, monitors2 = monitors2,
                          thin = 10, thin2 = 100, print = TRUE) # input the R model

# sample standard deviations on log scale
mcmcConf$removeSamplers(sigmas)
for (s in sigmas) {
  mcmcConf$addSampler(target = s, type = "RW", control = list(log = TRUE))
}

# 2. Build and compile the MCMC
Rmcmc <- buildMCMC(mcmcConf) # Set enableWAIC = TRUE if we need to calculate WAIC
Cmcmc <- compileNimble(Rmcmc)

# 3. Run MCMC
mcmc.out <- runMCMC(Cmcmc, inits = inits,
                    niter = 50000, nchains = 2, nburnin = 1000,
                    progressBar = TRUE, samples = TRUE, summary = TRUE)

# ----- SAVE OUTPUT SAMPLES AND SUMMARY -----
saveRDS(mcmc.out, file = "mcmc_out.rds")
