# Theo AO Rashid -- March 2020

# ----- BYM model -----
# Common terms (normal prior) +
# BYM for each LSOA +
# Age effects (random walk prior)
# --------------------

library(rgdal)
library(spdep)
library(dplyr)
library(nimble)
library(igraph)

set.seed(1)

# ----- IMPORT DATA -----
# Mortality data
# path <- "/rds/general/user/tar15/home/mortality-statsmodel/Data/mortsim.csv" # London
path <- "/Users/tar15/Dropbox/SPH/Data/Unit Test/mortsim_hf.csv" # Hammersmith and Fulham
mortality <- read.csv(file = path) %>%
  select(-X) # remove autogenerated column

mortality_m <- mortality %>% # Select male sex
  filter(sex == 1) %>%
  select(-sex)

# Lookup table
grid.lookup <- mortality_m %>% # lookup correct MSOA or LAD for that LSOA
  select(LSOA.id, MSOA.id, LAD.id) %>%
  distinct() %>%
  arrange(LSOA.id) # arrange ascending so matches loop order
grid.lookup <- as.matrix(grid.lookup) # grid.lookup[j, 2] for MSOA, grid.lookup[j, 3] for LAD

# Shape data
shapefile <- readOGR(dsn = "Data/shapefiles/ldn_LSOA11",
                layer = "LSOA11_London")

# Merge with mortality
colnames(shapefile@data)[1] <- "LSOA2011"
shapefile <- merge(shapefile, distinct(select(mortality_m, LSOA2011, LSOA.id, LAD.id)))
shapefile <- shapefile[!is.na(shapefile$LSOA.id) ,] # remove NA rows for subsetting (Hammersmith and Fulahm)
shapefile <- shapefile[order(shapefile$LSOA.id),] # reorder on LSOA.id
row.names(shapefile@data) <- shapefile@data$LSOA.id

# Extract adjacency matrix
W.nb <- poly2nb(shapefile, row.names = rownames(shapefile@data))
nbInfo <- nb2WB(W.nb)
# nbInfo$adj
# adj = nbInfo$adj, weights = nbInfo$weights, num = nbInfo$num
# s[1:N] ~ dcar_normal(adj[1:L], weights[1:L], num[1:N], tau, zero_mean = 0)
