# Theo AO Rashid -- May 2020

# ----- Hierarchical model -----
# Negative binomial likelihood
#
# Common terms (normal prior) +
# Random effects for each LAD (normal prior) +
# Random effects for each MSOA (normal prior, hierarchy) +
# Random effects for each LSOA (normal prior, hierarchy) +
# Age effects (random walk prior) +
# Age-LSOA interaction (normal prior) +
# Age-time interaction (random walk prior) +
# LSOA-time interaction (random walk prior)
#
# ONS hierarchy LSOA -> MSOA -> LAD
# --------------------

library(RCurl)
library(dplyr)
library(nimble)
library(lme4)

set.seed(1)

# ----- IMPORT DATA -----
# url <- getURL("https://media.githubusercontent.com/media/theorashid/mortality-statsmodel/master/Data/mortsim.csv") # London
url <- getURL("https://raw.githubusercontent.com/theorashid/mortality-statsmodel/master/Data/mortsim_hf.csv") # Hammersmith and Fulham
mortality <- read.csv(text = url) %>%
  select(-X) # remove autogenerated column

mortality_m <- mortality %>% # Select male sex
  filter(sex == 1) %>%
  select(-sex)

grid.lookup <- mortality_m %>% # lookup correct MSOA or LAD for that LSOA
  select(LSOA.id, MSOA.id, LAD.id) %>%
  distinct() %>%
  arrange(LSOA.id) # arrange ascending so matches loop order
grid.lookup <- as.matrix(grid.lookup) # grid.lookup[j, 2] for MSOA, grid.lookup[j, 3] for LAD

grid.lookup.MSOA <- mortality_m %>% # lookup correct LAD for that MSOA
  select(MSOA.id, LAD.id) %>%
  distinct() %>%
  arrange(MSOA.id) # arrange ascending so matches loop order
grid.lookup.MSOA <- as.matrix(grid.lookup.MSOA) # grid.lookup[j, 2] for LAD

# ----- INITIAL VALUES -----
# Get good initial values to avoid long burn ins.
# model with only age intercepts, LSOA intercepts and LSOA slopes
mod <- glmer(deaths ~ offset(log(population)) + YEAR.id + (1|age_group.id) + (1 + YEAR.id|LSOA.id), family = "poisson", data = subset(mortality_m, population > 0))

fixed <- coef(summary(mod))[, "Estimate"] # fixed effects
intercept <- fixed[1]
slope <- fixed[2]

bin <- ranef(mod)$LSOA.id
lsoa_int_inits <- bin$"(Intercept)"
lsoa_slope_inits <- bin$YEAR.id

bin <- ranef(mod)$age_group.id
age_inits <- bin$"(Intercept)"

initial <- list(intercept, slope, lsoa_int_inits, lsoa_slope_inits, age_inits)
names(initial) <- c("global.intercept", "global.slope", "lsoa.intercepts", "lsoa.slopes", "age.intercepts")

# Dimensions (Hammersmith and Fulham unit test second value):
# - age -- 19 (0, 1-4, 5-10, ..., 80-84, 85+)
# - LAD -- 33 or 1
# - MSOA -- 983 or 25
# - LSOA -- 4835 or 113
# - YEAR -- 14 (2004-17)

# ----- BUILD THE MODEL -----
# Indices:
# - a -- age
# - j -- space, each LSOA
# - t -- year (time)
code <- nimbleCode({
	# PRIORS
	
	# COMMON TERMS
	alpha0 ~ dnorm(0, 0.00001)
	beta0  ~ dnorm(0, 0.00001)
	# AREA TERMS -- random effects for intercepts and slopes
	# Lower level term centred on higher level
	# LAD terms
	for(j_LAD in 1:N_LAD){
		alpha_LAD[j_LAD] ~ dnorm(alpha0, sd = sigma_alpha_LAD) # centred on common terms
		beta_LAD[j_LAD] ~ dnorm(beta0, sd = sigma_beta_LAD)
	}
	sigma_alpha_LAD ~ dunif(0,2)
	sigma_beta_LAD  ~ dunif(0,2)
	
	# MSOA terms
	for(j_MSOA in 1:N_MSOA){
		alpha_MSOA[j_MSOA] ~ dnorm(alpha_LAD[grid.lookup.MSOA[j_MSOA, 2]], sd = sigma_alpha_MSOA) # centred on LAD terms
		beta_MSOA[j_MSOA] ~ dnorm(beta_LAD[grid.lookup.MSOA[j_MSOA, 2]], sd = sigma_beta_MSOA)
	}
	sigma_alpha_MSOA ~ dunif(0,2)
	sigma_beta_MSOA  ~ dunif(0,2)
	
	# LSOA terms
	for(j in 1:N_LSOA){ # j_LSOA = j
		alpha_LSOA[j] ~ dnorm(alpha_MSOA[grid.lookup[j, 2]], sd = sigma_alpha_LSOA) # centred on MSOA terms
		beta_LSOA[j]  ~ dnorm(beta_MSOA[grid.lookup[j, 2]], sd = sigma_alpha_LSOA)
	}
	sigma_alpha_LSOA ~ dunif(0,2)
	sigma_beta_LSOA  ~ dunif(0,2)
	
	# AGE TERMS
	alpha_age[1] <- 0 # initialise first terms for RW
	beta_age[1]  <- 0
	for(a in 2:N_age_groups){
		alpha_age[a] ~ dnorm(alpha_age[a-1], sd = sigma_alpha_age) # RW based on previous age group
		beta_age[a]  ~ dnorm(beta_age[a-1], sd = sigma_beta_age)
	}
	sigma_alpha_age ~ dunif(0,2)
	sigma_beta_age ~ dunif(0,2)
	
	# INTERACTIONS
	# age-LSOA interactions
	for(a in 1:N_age_groups){
		for(j in 1:N_LSOA){
			xi[a, j] ~ dnorm(alpha_age[a] + alpha_LSOA[j], sd = sigma_xi) # centred on age + LSOA term
		}
	}
	sigma_xi ~ dunif(0,2)
	
	# LSOA-time interactions
	for(j in 1:N_LSOA){
		nu[j, 1] <- 0
		for(t in 2:N_year){
			# the difference between timesteps is beta_v * time (where timestep length is 1 year)
			nu[j, t] ~ dnorm(nu[j, t-1] + beta_LSOA[j], sd = sigma_nu) # beta_v incorporates beta term
		}
	}
	sigma_nu ~ dunif(0,2)
	
	# age-time interactions
	for(a in 1:N_age_groups){
		gamma[a, 1] <- 0
		for(t in 2:N_year){
			# the difference between timesteps is beta_age * time (where timestep length is 1 year)
			gamma[a, t] ~ dnorm(gamma[a, t-1] + beta_age[a], sd = sigma_gamma)
		}
	}
	sigma_gamma ~ dunif(0,2)
	# Put all parameters together into indexed lograte with age-LSOA-time overdispersion term
	for(a in 1:N_age_groups){
		for(j in 1:N_LSOA){
			for(t in 1:N_year){
				lograte[a, j, t] <- xi[a, j] + nu[j, t] + gamma[a, t]
			}
		}
	}
	
	# LIKELIHOOD
	# N total number of cells, i.e. ages*years*areas(*sex)
	for (i in 1:N) {
		# y is number of deaths in that cell
		# mu is predicted number of deaths in that cell
		y[i] ~ dnegbin(p[i], r)
		p[i] <- r/(r + mu[i])
		log(mu[i]) <- log(n[i]) + lograte[age[i], LSOA[i], yr[i]]
	}
	r ~ dunif(0,50)
})

constants <- list(N = nrow(mortality_m),
                  N_year = n_distinct(mortality_m$YEAR),
                  N_LSOA = n_distinct(mortality_m$LSOA2011),
                  N_MSOA = n_distinct(mortality_m$MSOA2011),
                  N_LAD = n_distinct(mortality_m$LAD2011),
                  N_age_groups = n_distinct(mortality_m$age_group),
                  grid.lookup = grid.lookup,
                  grid.lookup.MSOA = grid.lookup.MSOA,
                  age = mortality_m$age_group.id,
                  LSOA = mortality_m$LSOA.id, 
                  yr = mortality_m$YEAR.id)
data <- list(y = mortality_m$deaths,
             n = mortality_m$population)

# Initial values for uninformative priors (top-level nodes)
# mu, lograte, alpha_age, beta_age not initialise
inits <- list(alpha0 = initial$global.intercept,
			  beta0 = initial$global.slope,
			  alpha_LSOA = initial$lsoa.intercepts,
			  beta_LSOA = initial$lsoa.slopes,
			  alpha_age = initial$age.intercepts,
              sigma_alpha_MSOA = 0.1, sigma_beta_MSOA = 0.1,
              sigma_alpha_LSOA = 0.1, sigma_beta_LSOA = 0.1,
              sigma_alpha_LAD = 0.1, sigma_beta_LAD = 0.1,
              sigma_alpha_age = 0.75, sigma_beta_age = 0.015,
              sigma_xi = 0.08, sigma_nu = 0.1,
              sigma_gamma = 0.1, r = 1.0)

# ----- CREATE THE MODEL -----
model <- nimbleModel(code = code, constants = constants, inits = inits, data = data) # model in R
# model$getNodeNames() # look at nodes of model's DAG
# model$plotGraph() # plot the DAG

# ----- COMPILE THE MODEL IN C-CODE -----
Cmodel <- compileNimble(model)

# ----- MCMC INTEGRATION -----
# Monitors
# Monitor the death rate per person to avoid 0 population issues
monitors <- c("lograte")
# Hyperparameter monitors to check covergence, with some thinning
sigmas <- c("sigma_alpha_LSOA", "sigma_beta_LSOA", "sigma_alpha_MSOA",
			"sigma_beta_MSOA", "sigma_alpha_LAD", "sigma_beta_LAD",
			"sigma_alpha_age", "sigma_beta_age", "sigma_xi",
			"sigma_nu", "sigma_gamma")
monitors2 <- c("alpha0", "beta0", "r", sigmas)

# CUSTOMISABLE MCMC -- configureMCMC, buildMCMC, compileNimble, runMCMC
# 1. MCMC Configuration -- can be customised with different samplers
mcmcConf <- configureMCMC(model = Cmodel,
                          monitors = monitors, monitors2 = monitors2,
                          thin = 10, thin2 = 100, print = TRUE) # input the R model

# sample standard deviations on log scale
mcmcConf$removeSamplers(sigmas)
for (s in sigmas) {
	mcmcConf$addSampler(target = s, type = "RW", control = list(log = TRUE))
}

# 2. Build and compile the MCMC
Rmcmc <- buildMCMC(mcmcConf) # Set enableWAIC = TRUE if we need to calculate WAIC
Cmcmc <- compileNimble(Rmcmc)

# 3. Run MCMC
mcmc.out <- runMCMC(Cmcmc,
                    niter = 50000, nchains = 2, nburnin = 1000,
                    progressBar = TRUE, samples = TRUE, summary = TRUE)

# ----- SAVE OUTPUT SAMPLES AND SUMMARY -----
saveRDS(mcmc.out, file = "mcmc_out.rds")