# Theo AO Rashid -- March 2020

# ----- Spatial hierarchical model -----
# Common terms +
# Random effects for each LAD +
# Random effects for each LSOA (hierarchy)
#
# ONS hierarchy LSOA -> MSOA -> LAD
# Only use LSOA -> LAD here
# --------------------

library(RCurl)
library(dplyr)
library(nimble)
library(igraph)

set.seed(1)

# ----- IMPORT DATA -----
# url <- getURL("https://media.githubusercontent.com/media/theorashid/mortality-statsmodel/master/Data/mortsim.csv") # London
url <- getURL("https://raw.githubusercontent.com/theorashid/mortality-statsmodel/master/Data/mortsim_hf.csv") # Hammersmith and Fulham
mortality <- read.csv(text = url) %>%
  select(-X) # remove autogenerated column

mortality_m <- mortality %>% # Select male sex
  filter(sex == 1) %>%
  select(-sex)

grid.lookup <- mortality_m %>% # lookup correct MSOA or LAD for that LSOA
  select(LSOA.id, MSOA.id, LAD.id) %>%
  distinct() %>%
  arrange(LSOA.id) # arrange ascending so matches loop order
grid.lookup <- as.matrix(grid.lookup) # grid.lookup[j, 2] for MSOA, grid.lookup[j, 3] for LAD

# Dimensions (Hammersmith and Fulham unit test second value):
# - age -- 19 (0, 1-4, 5-10, ..., 80-84, 85+)
# - LAD -- 33 or 1
# - MSOA -- 983 or 25
# - LSOA -- 4835 or 113
# - YEAR -- 14 (2004-17)

# ----- BUILD THE MODEL -----
# Indices:
# - a -- age
# - j -- space, each LSOA
# - t -- year (time)
code <- nimbleCode({
    # PRIORS

    # COMMON TERMS
    #dnorm is mean, precision
	alpha0 ~ dnorm(0, 0.00001)
	beta0  ~ dnorm(0, 0.00001)
    
    # AREA TERMS -- random effects for intercepts and slopes
	# When building up hierarchical models, for better mixing centre the lower 
    # level parameter on the higher level one rather than adding e.g. NOT alpha0+alpha[j]
    
    # LAD terms
    for(j_LAD in 1:N_LAD){
        alpha_LAD[j_LAD] ~ dnorm(alpha0, tau_alpha_LAD) # centred on common terms
        beta_LAD[j_LAD] ~ dnorm(beta0, tau_beta_LAD)
    }
    sigma_alpha_LAD ~ dunif(0,2)
	tau_alpha_LAD <- pow(sigma_alpha_LAD,-2)
	sigma_beta_LAD  ~ dunif(0,2)
	tau_beta_LAD  <- pow(sigma_beta_LAD,-2)

    # LSOA terms
	for(j in 1:N_LSOA){
        alpha1[j] ~ dnorm(alpha_LAD[grid.lookup[j, 3]], tau_alpha1) # centred on LAD terms
		beta1[j]  ~ dnorm(beta_LAD[grid.lookup[j, 3]], tau_beta1)
	}
	sigma_alpha1 ~ dunif(0,2)
	tau_alpha1 <- pow(sigma_alpha1,-2)
	sigma_beta1  ~ dunif(0,2)
	tau_beta1  <- pow(sigma_beta1,-2)

    # Put all parameters together into indexed lograte
	for(a in 1:N_age_groups){
        for(j in 1:N_LSOA){
            for(t in 1:N_year){
                # remember to centre your t to improve sampling performance
                # (cuts down correlation between parameters)
                # DO NOT make it a dynamic centrering
		        lograte[a, j, t] <- alpha1[j] + beta1[j] * (t - 8)
            }
        }
    }

    # LIKELIHOOD
    # N total number of cells, i.e. ages*years*areas(*sex)
    for (i in 1:N) {
        # y is number of deaths in that cell, assumed Poisson 
		# mu is predicted number of deaths in that cell
        y[i] ~ dpois(mu[i])
        log(mu[i]) <- log(n[i]) + lograte[age[i], LSOA[i], yr[i]]
    }
})

# need initial estimates for alpha0, beta0
constants <- list(N = nrow(mortality_m),
                  N_year = n_distinct(mortality_m$YEAR),
                  N_LSOA = n_distinct(mortality_m$LSOA2011),
                  N_LAD = n_distinct(mortality_m$LAD2011),
                  N_age_groups = n_distinct(mortality_m$age_group),
                  grid.lookup = grid.lookup)
data <- list(y = mortality_m$deaths,
             n = mortality_m$population, 
             age = mortality_m$age_group.id,
             LSOA = mortality_m$LSOA.id, 
             yr = mortality_m$YEAR.id)

# ----- CREATE THE MODEL -----
model <- nimbleModel(code = code, constants = constants, data = data) # model in R
# model$getNodeNames() # look at nodes of model's DAG
# model$plotGraph() # plot the DAG

# ----- COMPILE THE MODEL IN C-CODE -----
Cmodel <- compileNimble(model)

# ----- MCMC INTEGRATION -----
# Initial values for uninformative priors (top-level nodes)
# Other values will be set from the model and subsequent
# chains will begin using starting values where the 
# previous chain ended
inits <- function() list(alpha0 = rnorm(1,-5,1), beta0 = rnorm(1,-0.1,0.01),
                         sigma_alpha1 = runif(1, 0.01, 0.8), sigma_beta1 = runif(1, 0.01, 0.8),
                         sigma_alpha_LAD = runif(1, 0.01, 0.8), sigma_beta_LAD = runif(1, 0.01, 0.8))

# CUSTOMISABLE MCMC -- configureMCMC, buildMCMC, compileNimble, runMCMC
# 1. MCMC Configuration -- can be customised with different samplers
mcmcConf <- configureMCMC(model = model, print = TRUE) # input the R model

# 2. Build and compile the MCMC
Rmcmc <- buildMCMC(mcmcConf) # Set enableWAIC = TRUE if we need to calculate WAIC
Cmcmc <- compileNimble(Rmcmc)

# 3. Run MCMC
mcmc.out <- runMCMC(Cmcmc, inits = inits,
                    thin = 1, niter = 10000, nchains = 2, nburnin = 1000,
                    progressBar = TRUE, samples = TRUE, summary = TRUE)

# ----- SAVE OUTPUT SAMPLES AND SUMMARY -----
saveRDS(mcmc.out, file = "mcmc_out.rds")
